### ISSUE TITLE
Could not load content for https://unpkg.com/@d3ts/d3ts-us-map.min.js.map

### ISSUE THREAD

**Issue by tashrifbillah** [bratter/us-map#1]
https://github.com/bratter/us-map#installing

```javascript
<script src="https://unpkg.com/@d3ts/us-map"></script>
<script>
  const projection = d3ts.usMapProjection();
</script>
```

Runs into 
> DevTools failed to load SourceMap: Could not load content for https://unpkg.com/@d3ts/d3ts-us-map.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by bratter** [comment]
Thanks for the heads up. Incorrect `files` key in package.json causing sourcemaps to be generated but not published. I'll fix and republish shortly.

**Comment by tashrifbillah** [comment]
Thank Brendan. In the meantime, I used this:
https://github.com/stamen/geo-albers-usa-territories#readme

**Comment by bratter** [comment]
OK, should be good to go. Version 0.3.0 now up on npm.

FYI the alternative solution is a more lightweight choice. Two main differences:
1. I'm trying to (eventually :-)) make a set of composable tooling for interactive us-maps, so will have much more code if all you want is a simple static map.
2. Slightly different design choices on the projection - I condensed the contiguous US slightly to make room on the left of GU, MP, AS and give more breathing room for overlaid controls. So take your pick on what look is best for your need!
